// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Social_Media_API.Data;

#nullable disable

namespace Social_Media_API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20231010142348_DatabaseAndSeeding")]
    partial class DatabaseAndSeeding
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Social_Media_API.Models.CommentModels.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("PostID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PostID");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2023, 10, 10, 17, 23, 48, 463, DateTimeKind.Local).AddTicks(450),
                            Description = "Nisi rerum nulla tempora eos officia. Et facere non atque vitae numquam. Et rem omnis nulla ipsum in.",
                            PostID = 2
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2023, 10, 10, 17, 23, 48, 463, DateTimeKind.Local).AddTicks(640),
                            Description = "Nihil doloremque sit ab hic sed sit hic. Est eos voluptate illo quae incidunt. Alias numquam quidem ab rerum. Esse officiis repellat doloribus vero.",
                            PostID = 3
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2023, 10, 10, 17, 23, 48, 463, DateTimeKind.Local).AddTicks(790),
                            Description = "Dolorem neque repellendus nemo iusto repellendus rerum asperiores suscipit. Dolor et nobis sed accusamus. Minima eius quia sed. Sit nemo saepe aperiam laborum ducimus qui.",
                            PostID = 7
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2023, 10, 10, 17, 23, 48, 463, DateTimeKind.Local).AddTicks(900),
                            Description = "Maiores quam eaque dolore maxime consequatur dolore sint id. Eius nihil sit et quisquam est numquam ad.",
                            PostID = 4
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2023, 10, 10, 17, 23, 48, 463, DateTimeKind.Local).AddTicks(1110),
                            Description = "Provident provident fugiat voluptatem est eaque aut maiores. Minus libero suscipit qui et nostrum fugiat ab eos omnis.",
                            PostID = 9
                        });
                });

            modelBuilder.Entity("Social_Media_API.Models.PostModels.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2023, 10, 10, 17, 23, 48, 462, DateTimeKind.Local).AddTicks(8220),
                            Description = "Voluptatum necessitatibus voluptatem saepe mollitia ea minima voluptas. Eum sit labore non. Culpa quae aut natus perferendis hic ex nisi distinctio quod. In a impedit eum eaque. Eos alias officiis eos eum accusantium libero delectus quasi praesentium.",
                            ImageUrl = "",
                            Title = "Doloremque sit temporibus quia.",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2023, 10, 10, 17, 23, 48, 462, DateTimeKind.Local).AddTicks(8520),
                            Description = "Eligendi ducimus repellat. Molestias sed voluptatem ipsum esse culpa placeat. At temporibus ea qui ex qui. Modi eligendi et aperiam sequi quibusdam.",
                            ImageUrl = "",
                            Title = "Aspernatur quod nesciunt.",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2023, 10, 10, 17, 23, 48, 462, DateTimeKind.Local).AddTicks(8640),
                            Description = "Assumenda similique sit quis et ipsum est beatae. Dolor qui laudantium quisquam.",
                            ImageUrl = "",
                            Title = "Voluptas enim cupiditate aut.",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2023, 10, 10, 17, 23, 48, 462, DateTimeKind.Local).AddTicks(8790),
                            Description = "Quis enim suscipit sunt. Minus soluta est perferendis molestias excepturi libero. Omnis quos aperiam ad in fugit omnis.",
                            ImageUrl = "",
                            Title = "Tempore doloribus ratione ad.",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2023, 10, 10, 17, 23, 48, 462, DateTimeKind.Local).AddTicks(9010),
                            Description = "Et dolores minus voluptates. Sequi recusandae nam dolorum dicta provident reprehenderit vitae. Natus praesentium assumenda pariatur et odio ut. Qui earum soluta.",
                            ImageUrl = "",
                            Title = "Eveniet tenetur non.",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2023, 10, 10, 17, 23, 48, 462, DateTimeKind.Local).AddTicks(9120),
                            Description = "Nisi omnis laudantium. Est atque minus vel rerum reiciendis laboriosam reprehenderit nihil.",
                            ImageUrl = "",
                            Title = "Blanditiis eum quaerat.",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = new DateTime(2023, 10, 10, 17, 23, 48, 462, DateTimeKind.Local).AddTicks(9390),
                            Description = "Autem impedit asperiores et. Facere quos quia porro beatae reprehenderit. Sunt numquam sequi dolores consectetur suscipit voluptates quam quis. Et qui ut a.",
                            ImageUrl = "",
                            Title = "Fuga voluptatem voluptatum dolor.",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 8,
                            CreatedDate = new DateTime(2023, 10, 10, 17, 23, 48, 462, DateTimeKind.Local).AddTicks(9700),
                            Description = "Est quis aliquid enim ea qui molestias quaerat voluptas consequuntur. Quibusdam sed exercitationem voluptas rerum aperiam quis ab voluptas. Totam laboriosam dolore soluta est consequatur rerum explicabo magnam. Alias eos consequatur nesciunt. Consequatur dolorem voluptatem ut aut ad sapiente quo mollitia molestiae.",
                            ImageUrl = "",
                            Title = "Ab nobis quaerat.",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 9,
                            CreatedDate = new DateTime(2023, 10, 10, 17, 23, 48, 462, DateTimeKind.Local).AddTicks(9940),
                            Description = "Quo dolorem accusamus dolor. Illo ipsa repudiandae neque accusamus. Voluptates sapiente numquam deserunt sunt tempore quis. Sunt doloremque incidunt temporibus totam veritatis quia labore.",
                            ImageUrl = "",
                            Title = "Quo vitae blanditiis.",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 10,
                            CreatedDate = new DateTime(2023, 10, 10, 17, 23, 48, 463, DateTimeKind.Local).AddTicks(120),
                            Description = "Aperiam deleniti et molestias fugiat et. Hic explicabo possimus nemo et aut explicabo facilis.",
                            ImageUrl = "",
                            Title = "Libero quibusdam.",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Social_Media_API.Models.CommentModels.Comment", b =>
                {
                    b.HasOne("Social_Media_API.Models.PostModels.Post", "Post")
                        .WithMany()
                        .HasForeignKey("PostID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");
                });
#pragma warning restore 612, 618
        }
    }
}
