// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Social_Media_API.Data;

#nullable disable

namespace Social_Media_API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Social_Media_API.Models.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2023, 10, 5, 1, 41, 21, 408, DateTimeKind.Local).AddTicks(4850),
                            Description = "Velit in inventore commodi dolor dolores minus. Dolores quasi et dolore error eos rerum culpa commodi eos. Placeat at ut occaecati non.",
                            ImageUrl = "",
                            Title = "Rerum error."
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2023, 10, 5, 1, 41, 21, 408, DateTimeKind.Local).AddTicks(5230),
                            Description = "Unde eius sit nisi. Rerum qui eum quam animi unde. Laboriosam totam aliquid sed quis adipisci omnis est odit.",
                            ImageUrl = "",
                            Title = "Voluptatem exercitationem asperiores."
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2023, 10, 5, 1, 41, 21, 408, DateTimeKind.Local).AddTicks(5770),
                            Description = "Voluptatibus ut sunt quos beatae modi. Et ducimus dolores quis voluptas corrupti doloribus pariatur commodi dolores. Dolorem ut consequuntur. Corporis pariatur quibusdam iure sint. Perspiciatis et quaerat sint sunt dolorum quis ex rerum culpa.",
                            ImageUrl = "",
                            Title = "Reprehenderit quibusdam ut nulla."
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2023, 10, 5, 1, 41, 21, 408, DateTimeKind.Local).AddTicks(6020),
                            Description = "Non laborum consequuntur atque minus ut nihil hic quia repellat. Non dolores consequuntur ea maxime qui recusandae.",
                            ImageUrl = "",
                            Title = "In vero soluta harum."
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2023, 10, 5, 1, 41, 21, 408, DateTimeKind.Local).AddTicks(6350),
                            Description = "Assumenda quia cumque et sequi quia qui id at. Sunt voluptatem dolorem natus doloribus voluptatem molestias.",
                            ImageUrl = "",
                            Title = "Qui commodi voluptatem molestiae."
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2023, 10, 5, 1, 41, 21, 408, DateTimeKind.Local).AddTicks(6640),
                            Description = "Culpa sed numquam provident est quia deserunt officiis ab. Magni doloribus illo eos voluptatem. Quis commodi ipsam at illo.",
                            ImageUrl = "",
                            Title = "Non rerum corrupti."
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = new DateTime(2023, 10, 5, 1, 41, 21, 408, DateTimeKind.Local).AddTicks(7150),
                            Description = "Dicta facere nostrum at sequi sequi est. Unde velit facere quia tempore repellat molestiae iusto sit error. Excepturi vero fugiat quia accusantium nostrum reiciendis earum cum. Expedita qui cum culpa deserunt repellat quo nisi fuga.",
                            ImageUrl = "",
                            Title = "Facilis beatae id."
                        },
                        new
                        {
                            Id = 8,
                            CreatedDate = new DateTime(2023, 10, 5, 1, 41, 21, 408, DateTimeKind.Local).AddTicks(7600),
                            Description = "Beatae eum autem repellendus et quo quis. Qui itaque itaque voluptas repellat consectetur et et. Exercitationem quam voluptas quibusdam et. Velit quia omnis.",
                            ImageUrl = "",
                            Title = "At voluptatum fugit."
                        },
                        new
                        {
                            Id = 9,
                            CreatedDate = new DateTime(2023, 10, 5, 1, 41, 21, 408, DateTimeKind.Local).AddTicks(8110),
                            Description = "Eum est qui. Officiis enim nisi asperiores temporibus quia deserunt quod vitae sunt. Ut impedit non omnis qui nisi sed consequuntur. Voluptatem fugiat a. Sit velit quibusdam quasi similique voluptas libero et consequatur.",
                            ImageUrl = "",
                            Title = "Asperiores aperiam."
                        },
                        new
                        {
                            Id = 10,
                            CreatedDate = new DateTime(2023, 10, 5, 1, 41, 21, 408, DateTimeKind.Local).AddTicks(8680),
                            Description = "Ducimus qui alias et. Quaerat facilis maxime earum est suscipit est error quia voluptate. Rerum ut cum et harum aspernatur distinctio sequi. Accusantium in autem at incidunt ex.",
                            ImageUrl = "",
                            Title = "Eius enim ratione."
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
